### ISSUE TITLE
About the training details

### ISSUE THREAD

**Issue by henryccl** [LX-doctorAI1/M2KT#2]
Hello!  Thank you for sharing this interesting work. I would like to know what kind of GPUs you are experimenting on? And how long does it take for the proposed method to perform a training on IU-Xray dataset and MIMIC-CXR dataset respectively?

**Comment by LX-doctorAI1** [comment]
We train it on V-100 GPU.




&nbsp;









肖立

北京邮电大学/教职工/人工智能学院



北京




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "henryccl"; 
Date: 2023年4月25日(星期二) 下午4:24
To: "LX-doctorAI1/M2KT"; 
Cc: "Subscribed"; 
Subject: [LX-doctorAI1/M2KT] About the training details (Issue #2)

&nbsp;


 
Hello!  Thank you for sharing this interesting work. I would like to know what kind of GPUs you are experimenting on? And how long does it take for the proposed method to perform a training on IU-Xray dataset and MIMIC-CXR dataset respectively?

**Comment by henryccl** [comment]
> We train it on V-100 GPU. &nbsp; 肖立 北京邮电大学/教职工/人工智能学院 北京 &nbsp; &nbsp; &nbsp; ------------------&nbsp;Original&nbsp;------------------ From: "henryccl"; Date: 2023年4月25日(星期二) 下午4:24 To: "LX-doctorAI1/M2KT"; Cc: "Subscribed"; Subject: [LX-doctorAI1/M2KT] About the training details (Issue #2) &nbsp; Hello! Thank you for sharing this interesting work. I would like to know what kind of GPUs you are experimenting on? And how long does it take for the proposed method to perform a training on IU-Xray dataset and MIMIC-CXR dataset respectively? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

Thanks！
